name: Build LaTeX document
on:
  push:
    branches:
    - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "**/*.tex"
          glob_root_file: true
          work_in_root_file_dir: true
      - name: Release
        uses: CupOfTea696/gh-action-auto-release@v1
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
          regex: "/^Release: #{semver}$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
